### ISSUE TITLE
SeekToRow skips rows during compaction

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#294]
```
thor@thors-MacBook-Pro frostdb % go test -v -run XXX -bench Writers
goos: darwin
goarch: arm64
pkg: github.com/polarsignals/frostdb
Benchmark_Table_Insert_1000Rows_10Iters_10Writers
    table_test.go:427:
        	Error Trace:	table_test.go:427
        	            				table_test.go:307
        	Error:      	Not equal:
        	            	expected: 100000
        	            	actual  : 55634
        	Test:       	Benchmark_Table_Insert_1000Rows_10Iters_10Writers
--- FAIL: Benchmark_Table_Insert_1000Rows_10Iters_10Writers
```

After a git bisect it appears that https://github.com/polarsignals/frostdb/commit/017d5f6d9baff694ad147cdd15071feb367f71a0 is the offending commit @asubiotto

**Comment by asubiotto** [comment]
After investigating, it seems like it's the call to `SeekToRow` during compaction that "skips" over rows:
https://github.com/polarsignals/frostdb/blob/6e88c51f1a976c347c4877a2af2ff6bcbfeeafa7/compaction.go#L569

I'm not sure why, since the seek should be idempotent. I think we can remove it to fix this issue in the short term, but I'll try to reproduce and file an issue against upstream parquet.
