### ISSUE TITLE
Clarify that column names are sorted when schema is created.

### ISSUE THREAD

**Issue by joeblubaugh** [polarsignals/frostdb#95]
This set of column definitions:
```go
[]dynparquet.ColumnDefinition{
{
	Name:          "timestamp",
	StorageLayout: parquet.Int(64),
	Dynamic:       false,
},
{
	Name:          "state",
	StorageLayout: parquet.String(),
	Dynamic:       false,
},
{
	Name:          "labels",
	StorageLayout: parquet.Encoded(parquet.Optional(parquet.String()), &parquet.RLEDictionary),
	Dynamic:       true,
},
}
```
will actually have column indexes:
`{labels: 0, state: 1, timestamp: 2}`

So, when inserting fields, you must get the column indexes by searching the schema's column slice, rather than based on your own definition.

Documentation on functions and/or examples where this happens would be useful to new contributors. 

---
Aside: what is the reason that column names are sorted on schema creation?

**Comment by brancz** [comment]
We need to have them sorted so that when we merge two row groups with different dynamic columns we can perform a [k-way merge](https://en.m.wikipedia.org/wiki/K-way_merge_algorithm). We’ve been thinking about [improving the ergonomics](https://github.com/polarsignals/arcticdb/pull/67) of the insert API so that people don’t have to care about the index positions, but haven’t come up with anything satisfactory (yet).

Would you be willing to contribute some docs where it would have been helpful for you to understand that this sorting is happening?

**Comment by joeblubaugh** [comment]
Sure thing. I'll send a PR when I get a bit of spare time.

**Comment by brancz** [comment]
Done!

**Comment by joeblubaugh** [comment]
@metalmatze thanks, that's a helpful example.
